# The *with* keyword is standard in Python 2.6, but has to be explicitly imported in Python 2.5

# run a simple scan script to derive the horizon mask for KAT-7
# scan over constant elevation range but loop over azimuth

from __future__ import with_statement

import katuilib
from katuilib import CaptureSession
import uuid

import optparse
import sys
import numpy as np

# Parse command-line options that allow the defaults to be overridden
# Default KAT configuration is *local*, to prevent inadvertent use of the real hardware
parser = optparse.OptionParser(usage="usage: %prog [options]")
# Generic options
parser.add_option('-i', '--ini_file', dest='ini_file', type="string", default="cfg-local.ini", metavar='INI',
                  help='Telescope configuration file to use in conf directory (default="%default")')
parser.add_option('-s', '--selected_config', dest='selected_config', type="string", default="local_ff_2dish", metavar='SELECTED',
                  help='Selected configuration to use (default="%default")')
parser.add_option('-u', '--experiment_id', dest='experiment_id', type="string",
                  help='Experiment ID used to link various parts of experiment together (UUID generated by default)')
parser.add_option('-o', '--observer', dest='observer', type="string", help='Name of person doing the observation')
parser.add_option('-d', '--description', dest='description', type="string", default="Horizon mask data",
                  help='Description of observation (default="%default")')
parser.add_option('-a', '--ants', dest='ants', type="string", metavar='ANTS',
                  help="Comma-separated list of antennas to include in scan (e.g. 'ant1,ant2')," +
                       " or 'all' for all antennas - this MUST be specified (safety reasons)")
parser.add_option('-f', '--centre_freq', dest='centre_freq', type="float", default=1822.0,
                  help='Centre frequency, in MHz (default="%default")')
parser.add_option("-z", "--az", dest="az", type="string", default='0,360',
                 help='Azimuth angle along which to do horizom mask, in degrees (default="%default")')
parser.add_option('-e', '--el', dest='el', type="float", default=10.0,
                help='elevation angle along which to do horizon mask, in degrees (default="%default")')
# Experiment-specific options
(opts, args) = parser.parse_args()

# Various non-optional options...
if opts.ants is None:
    print 'Please specify the antennas to use via -a option (yes, this is a non-optional option...)'
    sys.exit(1)
if opts.observer is None:
    print 'Please specify the observer name via -o option (yes, this is a non-optional option...)'
    sys.exit(1)
if opts.experiment_id is None:
    # Generate unique string via RFC 4122 version 1
    opts.experiment_id = str(uuid.uuid1())

# Build KAT configuration, as specified in user-facing config file
# This connects to all the proxies and devices and queries their commands and sensors
kat = katuilib.tbuild(opts.ini_file, opts.selected_config)
start_azim = int(opts.az.split(',')[0])
stop_azim = int(opts.az.split(',')[1])
azim_size = np.abs(stop_azim - start_azim)
scan_duration = azim_size/1.0 # scan at one degree per second
center_azim = (stop_azim + start_azim)/2.0
offset = np.abs(stop_azim)

with CaptureSession(kat, opts.experiment_id, opts.observer, opts.description, opts.ants) as session:
    session.standard_setup(opts.centre_freq)
    # Iterate through azimuth and elevation angles
    for el in [opts.el]:
        session.scan('azel,%f,%f' % (center_azim,el),duration=scan_duration,scan_in_azimuth = True, start=-offset,end=offset)
        session.fire_noise_diode('coupler')