#pa  = katuilib.data.PlotAnimator()
#ap12 = kat.dh.sd.plot_waterfall('phase',product=(1,2,'VV'))
#ap13 = kat.dh.sd.plot_waterfall('phase',product=(1,3,'VV'))
#ap14 = kat.dh.sd.plot_waterfall('phase',product=(1,4,'VV'))
#ap23 = kat.dh.sd.plot_waterfall('phase',product=(2,3,'VV'))
#ap24 = kat.dh.sd.plot_waterfall('phase',product=(2,4,'VV'))
#ap34 = kat.dh.sd.plot_waterfall('phase',product=(3,4,'VV'))
#pa.add_plot('ap12',ap12)
#pa.add_plot('ap13',ap13)
#pa.add_plot('ap14',ap14)
#pa.add_plot('ap23',ap23)
#pa.add_plot('ap24',ap24)
#pa.add_plot('ap34',ap34)
#pa.animate_all()

#pa2  = katuilib.data.PlotAnimator()
#ap12m = kat.dh.sd.plot_waterfall('mag',product=(1,2,'VV'))
#ap13m = kat.dh.sd.plot_waterfall('mag',product=(1,3,'VV'))
#ap14m = kat.dh.sd.plot_waterfall('mag',product=(1,4,'VV'))
#ap23m = kat.dh.sd.plot_waterfall('mag',product=(2,3,'VV'))
#ap24m = kat.dh.sd.plot_waterfall('mag',product=(2,4,'VV'))
#ap34m = kat.dh.sd.plot_waterfall('mag',product=(3,4,'VV'))
#pa2.add_plot('ap12m',ap12m)
#pa2.add_plot('ap13m',ap13m)
#pa2.add_plot('ap14m',ap14m)
#pa2.add_plot('ap23m',ap23m)
#pa2.add_plot('ap24m',ap24m)
#pa2.add_plot('ap34m',ap34m)
#pa2.animate_all()


import katuilib
kat.dh.stop_sdisp()
kat.dh.start_sdisp()

pa3  = katuilib.data.PlotAnimator()
tp4 = kat.dh.sd.plot_time_series('mag',[0,1,8,9],end_time=-500,scale='linear',start_channel=10,stop_channel=500)
ph6 = kat.dh.sd.plot_time_series('phase',[(1,2,'VV'),(1,3,'VV'),(1,4,'VV'),(2,3,'VV'),(2,4,'VV'),(3,4,'VV')],start_channel=300,stop_channel=301,end_time=-500,scale='linear')
pa3.add_plot('tp4',tp4)
pa3.add_plot('ph6',ph6)
pa3.animate_all()